MVCAutentimisega3/MVCAutentimisega3/Models/Picture.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAutentimisega3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Picture()
        {
            this.Likes = new HashSet<Like>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int FileId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public bool Visibility { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DataFile DataFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
        public virtual Album Album { get; set; }
        public virtual Category Category { get; set; }
    }
}

MVCAutentimisega3/MVCAutentimisega3/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCAutentimisega3.Models;
using System.IO; //LISADA

namespace MVCAutentimisega3.Controllers
{
    public class PicturesController : Controller
    {
        private ParemEsimeneEntities db = new ParemEsimeneEntities();

        // GET: Pictures
        public ActionResult Index()
        {
            var pictures = db.Pictures.Include(p => p.AspNetUser).Include(p => p.DataFile).Include(p => p.Album).Include(p => p.Category);
            return View(pictures.ToList());
        }

        // GET: Pictures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // GET: Pictures/Create
        public ActionResult Create()
        
        {
            if (!Request.IsAuthenticated) return RedirectToAction("Index");
            AspNetUser user = db.AspNetUsers.Where(x => x.Email == User.Identity.Name).Single();

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Fullaame", user.Id); 


            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            //ViewBag.FileId = new SelectList(db.DataFiles, "Id", "Name"); // ei ole vaja
            ViewBag.AlbumId = new SelectList(db.Albums, "Id", "Name");
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View(new Picture { UserId = user.Id, Created = DateTime.Now });
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Name,Description,Created,Visibility,AlbumId,CategoryId")] Picture picture, HttpPostedFileBase file)
            // Siin lisasime, et tuleb fail ka
            // siit võtsime fileId ära
        {
            if (ModelState.IsValid)
            {
                if (ModelState.IsValid && file  != null && file.ContentLength>0)
                // Ma hakkan pilti salvestama ainult siis kui kõik väljad on täidetud, fail on olemas ja faili pikkus on suurem kui null. 

                using (BinaryReader reader = new BinaryReader(file.InputStream))
                // Lisame siia using bloki, et teeme seda ainult selle korra ja siis viskame mälust välja selle bloki käigus
                {
                    ; // see loeb http-ga saadetud faili sisu lugeda
                    byte[] buff = reader.ReadBytes(file.ContentLength); // loeme nad arrayssee buff. Loe nii palju, kui selle length o


                    //if (ModelState.IsValid)
                    {
                        DataFile dataFile = new DataFile
                        {
                            ContentType = file.ContentType,
                            Name = file.FileName.Split('\\').Last(), // võta failinimest vaid viimase osa peale \
                            Content = buff,
                        };

                        db.DataFiles.Add(dataFile);
                        db.SaveChanges();
                        // Sellel hetkel tekib DataFile Id ja ta pannakse DataFile tabelisse

                        picture.FileId = dataFile.Id;
                        db.Pictures.Add(picture);
                        db.SaveChanges(); 

                        return RedirectToAction("Index");
                    }
                }
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", picture.UserId);
            ViewBag.FileId = new SelectList(db.DataFiles, "Id", "Name", picture.FileId);
            ViewBag.AlbumId = new SelectList(db.Albums, "Id", "UserId", picture.AlbumId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", picture.CategoryId);
            return View(picture);
        }

        // GET: Pictures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", picture.UserId);
            ViewBag.FileId = new SelectList(db.DataFiles, "Id", "Name", picture.FileId);
            ViewBag.AlbumId = new SelectList(db.Albums, "Id", "UserId", picture.AlbumId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", picture.CategoryId);
            return View(picture);
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,FileId,Name,Description,Created,Visibility,AlbumId,CategoryId")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(picture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", picture.UserId);
            ViewBag.FileId = new SelectList(db.DataFiles, "Id", "Name", picture.FileId);
            ViewBag.AlbumId = new SelectList(db.Albums, "Id", "UserId", picture.AlbumId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", picture.CategoryId);
            return View(picture);
        }

        // GET: Pictures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Pictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.Pictures.Find(id);
            db.Pictures.Remove(picture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCAutentimisega3/MVCAutentimisega3/Views/Pictures/Create.cshtml
@model MVCAutentimisega3.Models.Picture

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Pictures", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
                @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Picture</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control", disabled = "Disabled" })
            @Html.HiddenFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.FileId, "FileId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("FileId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FileId, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div*@>
    @Html.Hidden("created")

    <div class="form-group">
        @Html.LabelFor(model => model.Visibility, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Visibility)
                @Html.ValidationMessageFor(model => model.Visibility, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AlbumId, "AlbumId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AlbumId", null,"--vali album--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, "--vali album--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    @*Siia lisame*@
    <label for="file"> Upload omage: </label>
    <input type="file" id="file" name="file" class="form-control" />


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCAutentimisega3/MVCAutentimisega3/Views/Pictures/Delete.cshtml
@model MVCAutentimisega3.Models.Picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visibility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFile.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFile.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCAutentimisega3/MVCAutentimisega3/Views/Pictures/Details.cshtml
@model MVCAutentimisega3.Models.Picture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Visibility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visibility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFile.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFile.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Album.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCAutentimisega3/MVCAutentimisega3/Views/Pictures/Edit.cshtml
@model MVCAutentimisega3.Models.Picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileId, "FileId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FileId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FileId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Visibility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Visibility)
                    @Html.ValidationMessageFor(model => model.Visibility, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumId, "AlbumId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlbumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCAutentimisega3/MVCAutentimisega3/Views/Pictures/Index.cshtml
@model IEnumerable<MVCAutentimisega3.Models.Picture>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Visibility)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.AspNetUser.FullName)*@
            Owner
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.DataFile.Name)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Album.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Visibility)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.FullName)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.DataFile.Name)*@
            <img width="100" src="@Url.Action("Content","DataFiles",new { id = item.FileId })"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Album.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>